version: 0.2
phases:
  build:
    commands:
      - echo Build started 
      - echo Building the Docker image...          
      - docker build -t x22-webapp-container:latest .

artifacts:
  files:
    - '**/*'
  name: x22-webapp-container 

